---
# PyCharm IDE installation

- name: Update package lists
  apt: update_cache=yes
  become: yes

- name: Intall needed libs
  apt: name={{item}} install_recommends=no
  become: yes
  with_items:
    - wget
    - git
    - default-jre
    - libxrender1
    - libxtst6
    - python
    - apt-utils

- name: Install PyCharm
  script: ../files/install_pycharm.sh {{pycharm_home}}
  become: yes

- name: Create easy access symlink
  file: src={{pycharm_home}}/bin/pycharm.sh dest=/usr/bin/pycharm state=link
  become: yes
  