---
# Playbook for repository installation check

- name: catkin clean workspace directories
  file: path={{item}} state=absent
  with_items:
    - "{{ros_workspace}}/build_isolated"
    - "{{ros_workspace}}/devel_isolated"
    - "{{ros_workspace}}/install_isolated"

- name: Set non-repository packages using lists substraction
  set_fact:
     non_repo_packages : "{{workspace_packages_names|difference(repo_packages_names)|join(';')}}"

- name: catkin make workspace in isolated fashion
  shell: bash -c "source <(grep '^export\|^source' {{ansible_env.HOME}}/.bashrc) && catkin_make_isolated && catkin_make"
    chdir={{ros_workspace}}

#- name: catkin install workspace in isolated fashion
#  shell: bash -c "source <(grep '^export\|^source' {{ansible_env.HOME}}/.bashrc) && catkin_make_isolated --install -DCATKIN_BLACKLIST_PACKAGES='{{ non_repo_packages }}'"
#    chdir={{ros_workspace}}
